spring.application.name=demo-webflux
settings.headers.validation.headers.[0].header-name=X-Additional-Required
settings.headers.validation.headers.[1].header-name=X-Additional-Optional
settings.headers.validation.headers.[1].required=false
settings.headers.validation.headers.[2].header-name=X-Additional-Custom-Validator
settings.headers.validation.headers.[2].required=false
# Spring bean name
settings.headers.validation.headers.[2].validator=CustomValidator
# will take precedence over the default header X-TimeStamp
settings.headers.validation.headers.[3].header-name=X-Timestamp
settings.headers.validation.headers.[3].required=false
settings.headers.validation.headers.[3].validator=co.ke.xently.demowebflux.validators.ISO8601TimestampHeaderValidator
settings.headers.validation.headers.[4].header-name=X-Custom-Allowed-Values
settings.headers.validation.headers.[4].allowed-values=x,y,z
settings.headers.validation.headers.[5].header-name=X-Custom-Allowed-Values-Optional
settings.headers.validation.headers.[5].required=false
settings.headers.validation.headers.[5].allowed-values=x,y,z
